### ISSUE TITLE
ctags fails to compile in gcc 4.5

### ISSUE THREAD

**Issue by vhda** [universal-ctags/ctags#466]
Compile fails with the following message:

```
gcc -I. -I. -I./main -DHAVE_CONFIG_H  -DDEBUG -DDATADIR=\"/remote/de02h25/vhugo/.local/ctags/share/ctags\" -DPKGCONFDIR=\"/remote/de02h25/vhugo/.local/ctags/etc/ctags\" -DPKGLIBEXECDIR=\"/remote/de02h25/vhugo/.local/ctags/libexec/ctags\" -g -O2 -Wall  -o main/entry.o -c main/entry.c
In file included from main/entry.c:43:0:
main/options.h:136:3: error: redefinition of typedef ‘OptionLoadingStage’
main/parse.h:21:34: note: previous declaration of ‘OptionLoadingStage’ was here
make: *** [main/entry.o] Error 1
```

**Update**
The following warnings also appear during the compile in this version of gcc:

```
gcc -I. -I. -I./main -DHAVE_CONFIG_H  -DDEBUG -DDATADIR=\"/remote/de02h25/vhugo/.local/ctags/share/ctags\" -DPKGCONFDIR=\"/remote/de02h25/vhugo/.local/ctags/etc/ctags\" -DPKGLIBEXECDIR=\"/remote/de02h25/vhugo/.local/ctags/libexec/ctags\" -g -O2 -Wall  -o main/parse.o -c main/parse.c
main/parse.c: In function ‘nominateLanguageCandidates’:
main/parse.c:213:14: warning: ‘spec’ may be used uninitialized in this function

gcc -I. -I. -I./main -DHAVE_CONFIG_H  -DDEBUG -DDATADIR=\"/remote/de02h25/vhugo/.local/ctags/share/ctags\" -DPKGCONFDIR=\"/remote/de02h25/vhugo/.local/ctags/etc/ctags\" -DPKGLIBEXECDIR=\"/remote/de02h25/vhugo/.local/ctags/libexec/ctags\" -g -O2 -Wall  -o main/tg.o -c main/tg.c
main/tg.c: In function ‘tg_nonalnum_get_char’:
main/tg.c:130:3: warning: implicit declaration of function ‘isblank’
```

**Comment by masatake** [comment]
I'm very sorry. I stop my rush.

**Comment by masatake** [comment]
Could you try the head?

**Comment by vhda** [comment]
That's not the reason, but I did spend some time to understand why this was also failing in that location. I'm preparing the fix, give me 2mn.

P.S. I really hate when you don't PR changes! ;P

**Comment by vhda** [comment]
@masatake I've updated the issue description. Could you analyze these for me, please?

**Comment by masatake** [comment]
> P.S. I really hate when you don't PR changes! ;P

I see. I will reduce PR-less commits.

**Comment by vhda** [comment]
Regarding the warnings:

1. Still exists but I think it is a false positive. Probably more recent gcc versions are able to understand this.
2. No longer shows.

@masatake if you agree we can close this ticket.

**Comment by masatake** [comment]
About 1. Could you try 
```
const char* spec = NULL;
````
?
If, this improves the situation, could you commit the change directly?

**Comment by vhda** [comment]
I don't agree with that change because the variable `spec` is always assigned a value before being used, so that would only be a waste of CPU cycles (well, a single cycle at most, but a waste nevertheless).

**Comment by masatake** [comment]
How about removing const like
```
char* spec;
```
?

**Comment by vhda** [comment]
Becomes:

```
gcc -I. -I. -I./main -DHAVE_CONFIG_H  -DDEBUG -DDATADIR=\"/remote/de02h25/vhugo/.local/ctags/share/ctags\" -DPKGCONFDIR=\"/remote/de02h25/vhugo/.local/ctags/etc/ctags\" -DPKGLIBEXECDIR=\"/remote/de02h25/vhugo/.local/ctags/libexec/ctags\" -g -O2 -Wall  -o main/parse.o -c main/parse.c
main/parse.c: In function ‘nominateLanguageCandidates’:
main/parse.c:219: warning: passing argument 3 of ‘getNameOrAliasesLanguageAndSpec’ from incompatible pointer type
```

Oh, wait... in `getNameOrAliasesLanguageAndSpec` the `else` is an `else if`!
In that case I'll just initialize `spec` as you initially proposed.
My bad, sorry! :)

**Comment by vhda** [comment]
One question: why doesn't gcc find this in more recent versions? Are we missing a `-W` option?

**Comment by vhda** [comment]
Second issue is showing again. Probably I did not `make clean` correctly before.
Apparently in the server I am compiling ctags, gcc is not assuming all C99 extensions so `isblank` is not available. If I add `-std=gnu99` to CFLAGS this warning disappears.

**Comment by masatake** [comment]
How about -std=c99 instead of -std=gnu99?

**Comment by vhda** [comment]
`-std=c99` isn't enough, for some reason. Although `man isblank` yelds:

       C89  specifies  isalnum(),  isalpha(),  iscntrl(), isdigit(), isgraph(), islower(), isprint(), ispunct(), isspace(), isupper(), and isxdigit(), but not isascii() and isblank().  POSIX.1-2001 also specifies those functions, and
       also isascii() (as an XSI extension) and isblank().  C99 specifies all of the preceding functions, except isascii().

       POSIX.1-2008 marks isascii() as obsolete, noting that it cannot be used portably in a localized application.

       POSIX.1-2008 specifies isalnum_l(), isalpha_l(), isblank_l(), iscntrl_l(), isdigit_l(), isgraph_l(), islower_l(), isprint_l(), ispunct_l(), isspace_l(), isupper_l(), and isxdigit_l().

       isascii_l() is a GNU extension.


But I've decided to make the code compatible with C89 instead. The solution is simple:
https://github.com/vhda/ctags/tree/main/fix-warnings

**Comment by vhda** [comment]
Given that these were real issues, I'm worried about newer versions of gcc not finding them. Any ideas?

**Comment by masatake** [comment]
The may page says:

```
       isblank():
           _XOPEN_SOURCE >= 600 || _ISOC99_SOURCE || _POSIX_C_SOURCE >= 200112L;
           or cc -std=c99
```

So I think -std=c99 is enough. Am I wrong?
I already used c99 syntax for initializing data structures. I would like to use it.

**Comment by vhda** [comment]
You are right. I've tested this again (I have such a bad memory! :P) and remembered why I used gnu99: we are using various GNU extensions in the code that result in the following warnings if we set the standard to POSIX C99.

```
main/entry.c:505: warning: implicit declaration of function ‘truncate’
main/parse.c:128: warning: implicit declaration of function ‘strcasecmp’
main/pcoproc.c:186: warning: implicit declaration of function ‘fdopen’
main/pcoproc.c:186: warning: assignment makes pointer from integer without a cast
main/pcoproc.c:198: warning: assignment makes pointer from integer without a cast
main/routines.c:405: warning: implicit declaration of function ‘lstat’
main/routines.c:838: warning: implicit declaration of function ‘mkstemp’
main/routines.c:853: warning: implicit declaration of function ‘fdopen’
main/routines.c:853: warning: assignment makes pointer from integer without a cast
main/sort.c:72: warning: implicit declaration of function ‘setenv’
main/strlist.c:168: warning: implicit declaration of function ‘strcasecmp’
main/tg.c:123: warning: implicit declaration of function ‘isascii’
parsers/ada.c:642: warning: implicit declaration of function ‘strncasecmp’
parsers/asp.c:69: warning: implicit declaration of function ‘strncasecmp’
parsers/beta.c:134: warning: implicit declaration of function ‘strcasecmp’
parsers/beta.c:189: warning: implicit declaration of function ‘strncasecmp’
parsers/eiffel.c:778: warning: implicit declaration of function ‘strcasecmp’
parsers/python.c:684: warning: implicit declaration of function ‘strdup’
parsers/python.c:684: warning: assignment makes pointer from integer without a cast
parsers/vhdl.c:327: warning: implicit declaration of function ‘strcasecmp’
parsers/vim.c:104: warning: implicit declaration of function ‘strncasecmp’
readtags.c:362: warning: implicit declaration of function ‘strdup’
readtags.c:362: warning: assignment makes pointer from integer without a cast
```

**Comment by masatake** [comment]
> Given that these were real issues, I'm worried about newer versions of gcc not finding them. Any ideas?

If you are talking about the null assignment to spec, newer gcc  may know 
```
 (*candidates)[count++].spec = spec;
```
is never an issue.
 getNameOrAliasesLanguageAndSpec returns a value other than LANG_IGNORE when the function assigns a value to spec.

```
 (*candidates)[count++].spec = spec;
```
is executed only if  getNameOrAliasesLanguageAndSpec returns a value other than LANG_IGNORE.

**Comment by vhda** [comment]
Good point! I did not notice that before.

**Comment by vhda** [comment]
@masatake what about `isblank`? Do you know why gcc 4.9 is not reporting it when using `-std=gnu89`? As far as I can tell that function should not exist in that C standard.

**Comment by masatake** [comment]
"2 Language Standards Supported by GCC" in gcc info:

```
The default, if no C language dialect options are
given, is '-std=gnu90'; this is intended to change to '-std=gnu11' in
some future release.
```

I guess the default is changed.

**Comment by vhda** [comment]
I tested by forcing both with `-std=gnu89` but still `isblank` is not reported as missing.

**Comment by vhda** [comment]
Resolved with #470
