### PR TITLE
build-sys: fix non-cross building packcc 

### LINKED ISSUE #2776: Compilation error in misc/packcc/packcc.c
When attempting a fresh compile on a Linux 3.10.0 system, with gcc 4.8.5, I am seeing the following error.

```
./misc/packcc/packcc.c: In function 'unescape_string':
./misc/packcc/packcc.c:414:21: error: 'for' loop initial declarations are only allowed in C99 mode
                     for (int k=0;k<4;k++) {
                     ^
./misc/packcc/packcc.c:414:21: note: use option -std=c99 or -std=gnu99 to compile your code
./misc/packcc/packcc.c:426:25: error: 'for' loop initial declarations are only allowed in C99 mode
                         for (int k=1;k<4;k++) ch = (ch << 4) | s[k];
                         ^
make[1]: *** [packcc] Error 1
make: *** [all] Error 2
```

This can be fixed with the following patch.
```diff
diff --git a/misc/packcc/packcc.c b/misc/packcc/packcc.c
index f61274d..ffbbc58 100644
--- a/misc/packcc/packcc.c
+++ b/misc/packcc/packcc.c
@@ -411,7 +411,8 @@ static bool unescape_string(char *str, size_t *length) {
                 }
                 {
                     char s[4];
-                    for (int k=0;k<4;k++) {
+                    int k;
+                    for (k=0;k<4;k++) {
                         char c = str[i + k + 1];
                         s[k] = (c >= '0' && c <= '9') ? c - '0' :
                                (c >= 'a' && c <= 'f') ? c - 'a' + 10 :
@@ -423,7 +424,8 @@ static bool unescape_string(char *str, size_t *length) {
                     }
                     else {
                         int ch=s[0];
-                        for (int k=1;k<4;k++) ch = (ch << 4) | s[k];
+                        int k;
+                        for (k=1;k<4;k++) ch = (ch << 4) | s[k];
                         if (ch < 0x80) {
                             str[j++] = (char)ch;
                         } else if (ch < 0x800) {
```

Requesting someone implement this fix to allow compilation on more systems.

### PR DESCRIPTION
**Pull request by masatake**
Close #2776.

@leleliu008, could you look at #2776?
My fix for this issue is cf828d2. Can I ask you to review the commit?

### CODE REVIEW

**Comment by leleliu008** [comment]
@masatake   Of course. I have reviewed your change and I confirmed everything is fine.

**Comment by masatake** [comment]
@leleliu008, thank you.
