### ISSUE TITLE
Compilation error in misc/packcc/packcc.c

### ISSUE THREAD

**Issue by raven42** [universal-ctags/ctags#2776]
When attempting a fresh compile on a Linux 3.10.0 system, with gcc 4.8.5, I am seeing the following error.

```
./misc/packcc/packcc.c: In function 'unescape_string':
./misc/packcc/packcc.c:414:21: error: 'for' loop initial declarations are only allowed in C99 mode
                     for (int k=0;k<4;k++) {
                     ^
./misc/packcc/packcc.c:414:21: note: use option -std=c99 or -std=gnu99 to compile your code
./misc/packcc/packcc.c:426:25: error: 'for' loop initial declarations are only allowed in C99 mode
                         for (int k=1;k<4;k++) ch = (ch << 4) | s[k];
                         ^
make[1]: *** [packcc] Error 1
make: *** [all] Error 2
```

This can be fixed with the following patch.
```diff
diff --git a/misc/packcc/packcc.c b/misc/packcc/packcc.c
index f61274d..ffbbc58 100644
--- a/misc/packcc/packcc.c
+++ b/misc/packcc/packcc.c
@@ -411,7 +411,8 @@ static bool unescape_string(char *str, size_t *length) {
                 }
                 {
                     char s[4];
-                    for (int k=0;k<4;k++) {
+                    int k;
+                    for (k=0;k<4;k++) {
                         char c = str[i + k + 1];
                         s[k] = (c >= '0' && c <= '9') ? c - '0' :
                                (c >= 'a' && c <= 'f') ? c - 'a' + 10 :
@@ -423,7 +424,8 @@ static bool unescape_string(char *str, size_t *length) {
                     }
                     else {
                         int ch=s[0];
-                        for (int k=1;k<4;k++) ch = (ch << 4) | s[k];
+                        int k;
+                        for (k=1;k<4;k++) ch = (ch << 4) | s[k];
                         if (ch < 0x80) {
                             str[j++] = (char)ch;
                         } else if (ch < 0x800) {
```

Requesting someone implement this fix to allow compilation on more systems.

**Comment by masatake** [comment]
Thank you. Reproduced on centos7. I will look into this.

**Comment by masatake** [comment]
To build ctags itself, c99 is needed. So instead of modifying packcc, I have tried to use c99 to build packcc.
See #2777.

**Comment by masatake** [comment]
If the issue is still reproduced, please, reopen this.

**Comment by raven42** [comment]
I'm requesting this be re-opened (I don't have permission as I'm not a member or collaborator).

Still seeing this error on some systems. Now I'm seeing it on a CentOS 6.9 setup (I know it's super old, but it's what I have to work with for now).

```
  CC     optlib/libctags_a-qemuhx.o
  CC     optlib/libctags_a-puppetManifest.o
  CC     optlib/libctags_a-scss.o
  CC     optlib/libctags_a-systemtap.o
  CC     main/libctags_a-debug.o
./misc/packcc/packcc.c: In function \u2018unescape_string\u2019:
./misc/packcc/packcc.c:414: error: \u2018for\u2019 loop initial declarations are only allowed in C99 mode
./misc/packcc/packcc.c:414: note: use option -std=c99 or -std=gnu99 to compile your code
./misc/packcc/packcc.c:426: error: \u2018for\u2019 loop initial declarations are only allowed in C99 mode
make[1]: *** [packcc] Error 1
make: *** [all] Error 2
```

System Info:
```
Linux <host> 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 26 17:51:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
```

Can I ask why we don't just fix the `packcc.c` file with the change I suggested? It is no functional impact and then there would be no need to worry about build scripts.

**Comment by masatake** [comment]
> Can I ask why we don't just fix the packcc.c file with the change I suggested? It is no functional impact and then there would be no need to worry about build scripts.

* We should not modify packcc.c for u-ctags specific reason (if possible):
  + packcc.c is written in C99.
  + we are moving to use packcc to the newly appeared upstream version from the Universal Ctags private versiono.
     (https://github.com/arithy/packcc/issues/13).
* CentOS6 has a stdc99 ready C compiler. 
* u-ctags assumes C99 compiler. (To be honest, it requires c99 + GNU extension.) 
* packcc was built well with -std=c99 option TILL we introduced a cross compilation feature.

Combining above items, I concluded this is an issue about our build-script.

I'm working on this topic in a container image. The change I made is working fine in the CentOS6 container and my note PC where Fedora33 runs. However, I wonder the change works well or not when making a ctags executable for ARM.
It will take more time and efforts than I assumed.

**Comment by leleliu008** [comment]
@raven42   there exists an immediate solution to this problem, you can use `CFLAGS_FOR_BUILD='-std=gnu99'` configure variable

@masatake I have fixed this problem and submit a PR.

**Comment by masatake** [comment]
@leleliu008, thank you. I shoud have talked to you when we received this issue report.
I would like you to consider joining u-ctags project (origanization) as a member.

I also tried to fix this issue, building ctags with autoconf-2.63 which is part of CentOS6.
However, the fix is very complicated.  I have not written some of commits log yet.
Anyway I would like to hear your comment about my pull request: https://github.com/universal-ctags/ctags/pull/2799.

**Comment by masatake** [comment]
This is the docker file I used for fixing this issue:

Dockerfile:
```
FROM centos:6

RUN sed -i "s|#baseurl=|baseurl=|g" /etc/yum.repos.d/CentOS-Base.repo \
  && sed -i "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-Base.repo \
  && sed -i "s|http://mirror\.centos\.org/centos/\$releasever|https://vault\.centos\.org/6.10|g" /etc/yum.repos.d/CentOS-Base.repo

RUN yum update -y
RUN yum install -y git gcc make autconf automake pkgconfig
RUN (cd /tmp; git clone https://github.com/universal-ctags/ctags)
```

I built a container image with:
```
# podman build -t centos6-yum .
```
Here . means the place where Dockerfile is. I guess you can use docker instead of podman. 

```
# podman run -ti centos6-yum /bin/bash
```
is for entring the CentOS environment.

**Comment by leleliu008** [comment]
@masatake  I have the `centos:6` docker image container instance. I have been took a quick look at your PR(https://github.com/universal-ctags/ctags/pull/2799). I think there is no need too much change. You can take a look at my PR(https://github.com/universal-ctags/ctags/pull/2798).

**Comment by masatake** [comment]
@leleliu008, thank you. Could you give me time (a week or so)? I consumed all my spare time for developing #2799.

**Comment by leleliu008** [comment]
@masatake Certainly.

**Comment by k-takata** [comment]
Closed by #2798.
