### ISSUE TITLE
error: redefinition of typedef ‘tagEntryInfo’

### ISSUE THREAD

**Issue by fortran-favors-the-old** [universal-ctags/ctags#699]
Unfortunately, recent revisions fail to build on my CentOS 6.5 system.  I used `git bisect` to determine that build failures began with revision e2755fded37efe060c8b260c07ecafaeaeb1d9e7.  Here's the error message emitted by GCC 4.4.7 when building e2755fded37efe060c8b260c07ecafaeaeb1d9e7:

    In file included from main/debug.h:20,
                     from main/args.c:20:
    main/entry.h:104: error: redefinition of typedef ‘tagEntryInfo’
    main/kind.h:23: note: previous declaration of ‘tagEntryInfo’ was here
    make: *** [main/args.o] Error 1
    make: *** Waiting for unfinished jobs....
    In file included from main/debug.h:20,
                     from main/entry.c:39:
    main/entry.h:104: error: redefinition of typedef ‘tagEntryInfo’
    main/kind.h:23: note: previous declaration of ‘tagEntryInfo’ was here

I get the same error message when building master (currently 8009da7753b177fdc56d3284f71b5f63178a362a), except for different line numbers.

I'm not sure how to fix this, so I'm hoping that this is simple enough for someone else to fix.

Thanks for developing Universal Ctags!

**Comment by masatake** [comment]
@fortran-favors-the-old, hi, again. Your account name is very impressive, so I can remember you quickly.

I introduced the typedef to avoid circular header file inclusion.
I think there is no good way without adding new header file where the typedef is put to solve this issue.

We are working hard on converting the build-system now. After we introduce automake successfully, I will work on this issue.

**Comment by fortran-favors-the-old** [comment]
@masatake: Okay, thank you!

**Comment by masatake** [comment]
Feel free to reopen this if my commit doesn't fix your issue.

**Comment by fortran-favors-the-old** [comment]
Works for me. Thanks for fixing this!
